### ISSUE TITLE
第4章 HBase 2日目　P105 Wikipediaをインポートできない

### ISSUE THREAD

**Issue by yumomo2010sky** [ohmsha/seven-databases-ja#12]
P105のコード
curl http://dumps.wikimedia.org/jawiki/latest/jawiki-latest-pages-meta-current.xml.bz2 | bzcat | $HBASE_HOME/bin/hbase shell import_from_wikipedia.rb
を入力したら、以下のようなエラーが出ました。どうしたら、よろしいでしょうか？

NativeException: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 10 actions: NotServingRegionException: 10 times, servers with issues: ubuntu:39735, 
  (root) at ./import_from_wikipedia.rb:48
    load at org/jruby/RubyKernel.java:1063
  (root) at /home/yuta/hbase-0.94.27/bin/hirb.rb:156
curl: (23) Failed writing body (3434 != 11680)

マシーンのスペック
ubuntu
HBase0.9427

**Comment by kdmsnr** [comment]
1日目のスクリプト（put_multiple_columns.rb）は、正常に動作したという前提でよろしいでしょうか。

その場合、上記のコマンドを入力したあとに、以下のようなメッセージは表示されましたでしょうか（NativeException...というエラーメッセージが表示される前になります）。

```
500 records inserted ...
1000 records inserted  ...
```

**Comment by yumomo2010sky** [comment]
ご返答いただき、ありがとうございます。

実行できなかった原因は、zookeeperの設定が適切ではなかったため、regionserverが起動していなかったためです。
現時点では、./hbase shell put_multiple_columns.rbで実行結果を確認できた後、import_from_wikipedia.rbを実行結果が適切であることを確認できました。

お騒がせして申し訳ありませんでした。

>1日目のスクリプト（put_multiple_columns.rb）は、正常に動作したという前提でよろしいでしょうか。
->./hbase shell put_multiple_columns.rbでは実行できなかったので、./hbase shellでシェルを立ち上げてから、スクリプトを実行していました。
